"""add app_version lineage fields

Revision ID: 0933bd48a905
Revises: 9f6b3b7b6b10
Create Date: 2026-01-05 16:58:48.620074

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0933bd48a905"
down_revision: Union[str, Sequence[str], None] = "9f6b3b7b6b10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "app_versions", sa.Column("previous_version_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "app_versions",
        sa.Column("release_date", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column("app_versions", sa.Column("change_log", sa.Text(), nullable=True))
    op.create_index(
        op.f("ix_app_versions_previous_version_id"),
        "app_versions",
        ["previous_version_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_app_versions_previous_version_id",
        "app_versions",
        "app_versions",
        ["previous_version_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_app_versions_previous_version_id", "app_versions", type_="foreignkey"
    )
    op.drop_index(
        op.f("ix_app_versions_previous_version_id"), table_name="app_versions"
    )
    op.drop_column("app_versions", "change_log")
    op.drop_column("app_versions", "release_date")
    op.drop_column("app_versions", "previous_version_id")
    # ### end Alembic commands ###
