"""empty message

Revision ID: 618517873f70
Revises:
Create Date: 2025-12-04 17:16:04.714061

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "618517873f70"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evaluations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("app_path", sa.String(), nullable=True),
        sa.Column("app_url", sa.String(), nullable=True),
        sa.Column(
            "app_type",
            sa.Enum("desktop_app", "web_app", name="apptype"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "GENERATING",
                "ASSIGNED",
                "IN_PROGRESS",
                "READY",
                "COMPLETED",
                "FAILED",
                name="evaluationstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("execution_mode", sa.String(), nullable=False),
        sa.Column("assigned_executor_id", sa.String(), nullable=True),
        sa.Column("results", sa.JSON(), nullable=True),
        sa.Column("local_application_path", sa.String(), nullable=True),
        sa.Column("high_level_goal", sa.String(), nullable=True),
        sa.Column("run_on_current_screen", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_evaluations_assigned_executor_id"),
        "evaluations",
        ["assigned_executor_id"],
        unique=False,
    )
    op.create_index(op.f("ix_evaluations_id"), "evaluations", ["id"], unique=False)
    op.create_table(
        "test_plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("evaluation_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "GENERATING", "READY", "COMPLETED", name="testplanstatus"
            ),
            nullable=False,
        ),
        sa.Column("summary", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["evaluations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_test_plans_evaluation_id"),
        "test_plans",
        ["evaluation_id"],
        unique=False,
    )
    op.create_index(op.f("ix_test_plans_id"), "test_plans", ["id"], unique=False)
    op.create_table(
        "test_cases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("evaluation_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("input_data", sa.JSON(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "ASSIGNED",
                "IN_PROGRESS",
                "COMPLETED",
                "FAILED",
                name="testcasestatus",
            ),
            nullable=False,
        ),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("execution_order", sa.Integer(), nullable=True),
        sa.Column("assigned_executor_id", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["evaluations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["test_plans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_test_cases_assigned_executor_id"),
        "test_cases",
        ["assigned_executor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_test_cases_evaluation_id"),
        "test_cases",
        ["evaluation_id"],
        unique=False,
    )
    op.create_index(op.f("ix_test_cases_id"), "test_cases", ["id"], unique=False)
    op.create_index(
        op.f("ix_test_cases_plan_id"), "test_cases", ["plan_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_test_cases_plan_id"), table_name="test_cases")
    op.drop_index(op.f("ix_test_cases_id"), table_name="test_cases")
    op.drop_index(op.f("ix_test_cases_evaluation_id"), table_name="test_cases")
    op.drop_index(op.f("ix_test_cases_assigned_executor_id"), table_name="test_cases")
    op.drop_table("test_cases")
    op.drop_index(op.f("ix_test_plans_id"), table_name="test_plans")
    op.drop_index(op.f("ix_test_plans_evaluation_id"), table_name="test_plans")
    op.drop_table("test_plans")
    op.drop_index(op.f("ix_evaluations_id"), table_name="evaluations")
    op.drop_index(op.f("ix_evaluations_assigned_executor_id"), table_name="evaluations")
    op.drop_table("evaluations")
    # ### end Alembic commands ###
